### PR TITLE
Fix important formatting problems lead to confusion #29

### PR DESCRIPTION
**Pull request by petarvujovic98**
Escape underscores in chapters that have unescaped underscores

### CODE REVIEW

**Comment by ryancwalsh** [comment]
This was fast :-)

Can you please always add here in the PR conversation screenshots from "before" and "after"?

That way, the reviewer (I in this case) will not necessarily need to pull the branch and run it locally. Thanks.

**Comment by petarvujovic98** [comment]
Yeah, no problem. Here they are:

**Before**:

Chapter 7:
Screenshot_03-03-2022_15:41:29

Chapter 6:
Screenshot_03-03-2022_15:39:18

**After**:

Chapter 7:
Screenshot_03-03-2022_15:40:40

Chapter 6:
Screenshot_03-03-2022_15:38:28

**Comment by ryancwalsh** [comment]
Cool. Thanks. Looks great.

I'll approve it. But actually, before I do, would you mind fixing an unrelated typo I noticed? 

memeLIst should have lowercase "i".

Thanks.

**Comment by petarvujovic98** [comment]
I believe I got it

**Before**:

Screenshot_03-03-2022_15:51:21

**After**:

Screenshot_03-03-2022_15:51:36

**Comment by ryancwalsh** [comment]
@petarvujovic98 I just noticed your commit message for https://github.com/NEAR-Edu/near.academy/commit/0e1a31b924685f7a0ab5d7b646d532c59d6ba5cc

Thanks for tagging the issue #. We always want to do that. Going forward, please also write an actual commit message too so that people have a quick reference and don't need to click through to the issue.

One possibility here would be `Fix underscore formatting problems that lead to confusion (see #29)`

**Comment by petarvujovic98** [comment]
Will do that. Thank you for the advice

**Pull request merged**
